mysite/myapp/urls.py
from django.urls import path
from myapp import views

app_name = "myapp"

urlpatterns = [
       path('', views.index),
       path('<int:my_id>/', views.indexItem, name='item'),
       #path('contacts/', views.contacts)
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include("myapp.urls", namespace="myapp"))
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mysite/myapp/models.py
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    description = models.CharField(max_length=200)
    image = models.ImageField(blank=True, upload_to='images')

    def __str__(self):
        return self.name

mysite/myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Product

def index(request):
    items = Product.objects.all()
    context = {
        'items':items
    }
    return render(request,'myapp/index.html', context)

def indexItem(request, my_id):
    try:
        item = Product.objects.get(id=my_id)
        context = {'item': item}
        return render(request, 'myapp/item.html', context=context)
    except Product.DoesNotExist:
        return HttpResponse("Item not found", status=404)


#def contacts(request):
   # return render(request,'myapp/contacts.html')

    

mysite/myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'myapp/styles.css' %}">
    <title>Document</title>
</head>
<body>
     {% include "myapp/navbar.html" %}
    {% block content %}
         text
    {% endblock content %}
</body>
</html>

mysite/myapp/templates/myapp/contacts.html
<html>
    <head>
    </head>
    <body>
        <h1>It`s our contacts</h1>
    </body>
</html>

mysite/myapp/templates/myapp/index.html
{% extends "myapp/base.html" %}

{% block content %}




<main class="mt-10 mx-auto max-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">
    <div class="sm:text-center lg:text-left">
        <h1 class="text-4xl font-extrabold text-gray-900 sm:text-5xl md:text-6xl">
            <span class="block xl:inline">Эсклюзивные товары</span>
            <span class="block xl:inline text-green-500">По Супер Ценам</span>
        </h1>
        <p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">Вы можете заказать товар из любой точки мира. Доставка включена</p>
    </div>
</main>

<div class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 xl:grid-col-3 lg:grid-col-3 gap-3">
            {%for item in items%}
            <a href="{% url 'myapp:item' item.id %}">
                <div class=" rounded overflow-hidden shadow-lg">
                    <img class="w-full h-[400px] object-fit:cover" src="{{ item.image.url }}" alt=""/>  <div class="">
                        <p class="font-bold text-xl mb-2">{{item.name}}</p>
                        <p class="font-bold text-xl text-green-500 mb-2">{{item.price}}</p>
                        <p class="text-gray-700 text-base">{{ item.description}}</p>
                    </div>
                </div>
            </a>
            {% endfor %}
</div>
        {% endblock content %}

mysite/myapp/templates/myapp/item.html
{% extends "myapp/base.html" %}
{% load humanize %}

{% block content %}
<div class="flex p-10 w-full h-200">
  <img class="w-1/3" src="{{ item.image.url }}" alt="itemPhoto">
  <div class="w-2/3 text-xl ml-10 mt-5">
    <p class="mt-5">{{ item.name }}</p>
    <p class="mt-5 text-green-500">$ {{ item.price }}</p>
    <p class="mt-5 text-gray-600">{{ item.description }}</p>
  </div>
</div>
{% endblock content %}

mysite/myapp/templates/myapp/navbar.html
{% load static %}

<nav class="bg-white shadow-lg">
    <div class="max-w-6xl mx-auto px-4">
        <div class="flex justify-between"> 
            <div class="flex space-x-7">
                <div class="flex">
                    <a href="#" class="flex items-center px-2 pu-4">
                    <img class="h-8 w-8" src="{% static 'myapp/img/shop.png' %}" alt="logo"/>
                    <span class="text-gray-500 font-semibold text-xl">Pro Shop</span> 
                </a>
                </div>
                <div class="items-center flex space-x-1">
                    <a href="#" class="py-4 px-2 text-gray-500 font-semibold">Home</a>
                    <a href="#" class="py-4 px-2 text-gray-500 font-semibold">About</a>
                    <a href="#" class="py-4 px-2 text-gray-500 font-semibold">Contacts</a>
                </div>
            </div>
        </div>
    </div>
</nav>